name: BlockReplacer
version: 1.0.0
main: com.ntust.camp.blockreplacer.BlockReplacerPlugin
api-version: 1.18
description: Replace blocks around you with bedrock
author: NTUST_CSIE_CAMP
website: https://github.com/WuSandWitch/NTUST-CSIE-CAMP-vulnerable-plugins

commands:
  br:
    description: Replace blocks around you with bedrock
    usage: /br <block>
    aliases: [br_y, br_target]

permissions:
  blockreplacer.use:
    description: Allows using /br command
    default: true
